//Helper file for Rest Client extension in VsCode

POST http://localhost:7071/api/ToEventGrid HTTP/1.1
content-type: application/json

[
  {
    "destinationId": "campus-1",
    "data": "1"
  },
  {
    "destinationId": "campus-3",
    "data": "3"
  }
]

### 

POST http://localhost:7071/api/ToServiceBus HTTP/1.1
content-type: application/json

[
  {
    "destinationId": "campus-1",
    "data": "1"
  },
  {
    "destinationId": "campus-2",
    "data": "2"
  },
  {
    "destinationId": "campus-1",
    "data": "3"
  }
]


###

POST http://localhost:7071/api/ToEventGrid HTTP/1.1
content-type: application/json

[
   {
     "destinationId": "campus-1",
     "data": "2"
   },
   {
     "destinationId": "campus-2",
     "data": "2"
   }
]